// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Info struct {
	// Types that are valid to be assigned to Value:
	//
	//	*Info_User
	//	*Info_Name
	Value                isInfo_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_8c158811749acb0d, []int{0}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

type isInfo_Value interface {
	isInfo_Value()
}

type Info_User struct {
	User string `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type Info_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*Info_User) isInfo_Value() {}

func (*Info_Name) isInfo_Value() {}

func (m *Info) GetValue() isInfo_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Info) GetUser() string {
	if x, ok := m.GetValue().(*Info_User); ok {
		return x.User
	}
	return ""
}

func (m *Info) GetName() string {
	if x, ok := m.GetValue().(*Info_Name); ok {
		return x.Name
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Info) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Info_OneofMarshaler, _Info_OneofUnmarshaler, _Info_OneofSizer, []interface{}{
		(*Info_User)(nil),
		(*Info_Name)(nil),
	}
}

func _Info_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Info)
	// value
	switch x := m.Value.(type) {
	case *Info_User:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.User)
	case *Info_Name:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case nil:
	default:
		return fmt.Errorf("Info.Value has unexpected type %T", x)
	}
	return nil
}

func _Info_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Info)
	switch tag {
	case 1: // value.user
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Info_User{x}
		return true, err
	case 2: // value.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Info_Name{x}
		return true, err
	default:
		return false, nil
	}
}

func _Info_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Info)
	// value
	switch x := m.Value.(type) {
	case *Info_User:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.User)))
		n += len(x.User)
	case *Info_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Info)(nil), "main.Info")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_8c158811749acb0d) }

var fileDescriptor_user_8c158811749acb0d = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2, 0xe6, 0x62,
	0xf1, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe1, 0x62, 0x01, 0xc9, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x7a, 0x30, 0x04, 0x81, 0x79, 0x20, 0xd1, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x98, 0x28, 0x88,
	0xe7, 0xc4, 0xce, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x9a, 0xc4, 0x06, 0x36, 0xc9, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x05, 0x70, 0x9c, 0x57, 0x00, 0x00, 0x00,
}
